### PR TITLE
DMIParser tests

### PR DESCRIPTION
**Pull request by Aavild**

### CODE REVIEW

**Review by Emilorzz — APPROVED** [review]
finally.. looks fine tho

**Review by Emilorzz — APPROVED** [review]
yes girl

**Review by AleksanderRDL — APPROVED** [review]
yes

**Review by frederikja163 — APPROVED** [review]
Ideally you would not just test if the data has been read correctly and not just if any data has been read. But otherwise this looks like an awesome PR. Good job making more topdown programming, really simplifies the code!

**Pull request merged**
